SUBROUTINE TINTERP(TMP,PRC,RSD,SHM,WND,PRS,OZN,INTMXp,INTMX,INTMXn,INTMNp,INTMN,INTMNn,INPRC,INRSD,INSHM,INWND,INPRS,INOZN,PDOY,DOY,NDOY,HOUR,LAT,TRES,INTSINB,WND_HGT)

  IMPLICIT NONE

!  [PHYSICAL CONSTAT]
  include "./param.inc"

!  [OUTPUT]
  REAL*8 TMP
  REAL*8 RSD
  REAL*8 PRC
  REAL*8 PRS
  REAL*8 WND
  REAL*8 SHM
  REAL*8 OZN

!  [INPUT]
  INTEGER DOY
  INTEGER PDOY
  INTEGER NDOY

  REAL*8 HOUR
  REAL*8 LAT
  
  INTEGER TRES

  REAL*8 INTSINB
  REAL*8 WND_HGT

  REAL*8 INTMXp
  REAL*8 INTMX
  REAL*8 INTMXn
  REAL*8 INTMNp
  REAL*8 INTMN
  REAL*8 INTMNn
  REAL*8 INRSD
  REAL*8 INPRC
  REAL*8 INPRS
  REAL*8 INWND
  REAL*8 INSHM
  REAL*8 INOZN

!  [INTERNAL]
  REAL*8 TSET
  REAL*8 NT

  REAL*8 DL
  REAL*8 DLP

!  [FUNCTION]
  REAL*8 DAYL
  REAL*8 SINB

  DL = DAYL(DOY,LAT)
  DLP= DAYL(PDOY,LAT)
  
  WND=INWND*DLOG(2.D0/0.05D0)/DLOG(WND_HGT/0.05D0)   !! WDNHGT to 2m
  PRS=INPRS
  PRC=INPRC
  SHM=INSHM

  IF(INTSINB>0.D0)THEN
     RSD=INRSD*86400.D0 * SINB(DOY,HOUR,LAT)  / INTSINB      !! = ((INRSD*86400.D0) * (SINB(DOY,HOUR,LAT) * DBLE(TRES) / INTSINB)) / DBLE(TRES)
  ELSE
     RSD=0.D0
  END IF

! WRITE(*,"(I5,A,F15.1,A,F15.5,A,F15.5,A,F15.5,A,F15.5,A,F15.5,A,F15.5A,F15.5)"),DOY,',',HOUR,',',INTMNn,',',INTMN,',',INTMX,',',TSET,',',TMP,',',HOURTMX,',',RSD                       
  !! Interpolation according to the method in Goudriaan (1994) P34
  IF(HOUR < (12.D0-DL*0.5D0))THEN
     TSET = INTMNp + (INTMXp - INTMNp) * DSIN(PI*DLP/(DLP+2.D0*HOURTMX))
     NT = 24.D0 - DL !night time
     TMP = (INTMN-TSET*Dexp(-NT/NocT)+(TSET-INTMN)*Dexp(-(HOUR+24.D0-(12.D0+DLP*0.5D0))/NocT)) / (1.D0-Dexp(-NT/NocT))
  ELSE IF( HOUR < (12.D0 + DL*0.5D0 )  )THEN
     TMP = INTMN + (INTMX - INTMN) * DSIN(PI*(HOUR-12.D0+DL*0.5D0)/(DL+2.D0*HOURTMX))
  ELSE
     TSET = INTMN + (INTMX - INTMN) * DSIN(PI*DL/(DL+2.D0*HOURTMX))
     NT = 24.D0 - DL !night time
     TMP = (INTMNn-TSET*Dexp(-NT/NocT)+(TSET-INTMNn)*Dexp(-(HOUR-(12.D0+DL*0.5D0))/NocT))/(1.D0-Dexp(-NT/NocT))
  END IF
 
! WRITE(*,"(I5,A,F15.1,A,F15.5,A,F15.5,A,F15.5,A,F15.5,A,F15.5,A,F15.5A,F15.5)"),DOY,',',HOUR,',',INTMNn,',',INTMN,',',INTMX,',',TSET,',',TMP,',',HOURTMX,',',RSD                       
 
  TMP = TMP + 273.15D0

  !!                    OZN=(INOZN(ILON,ILAT,IHOUR))  !OZN
  OZN=0.D0
  !! !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  
!  IF(WND<=0.D0)THEN
!     WND=0.01D0
!  END IF
  IF(SHM<=0.D0)THEN
     SHM=0.00001D0
  END IF
  


END SUBROUTINE TINTERP
